[workspace]
resolver = "2"
members = [
    "crates/k8socks-cli",
    "crates/k8socks-config",
    "crates/k8socks-k8s",
    "crates/k8socks-ssh",
    "crates/k8socks-logging", "crates/k8socks-traits",
]

[workspace.dependencies]
anyhow = "1.0.82"
tokio = { version = "1.37.0", features = ["full"] }
