[package]
name = "k8socks-ssh"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
k8socks-config = { version = "0.1.0", path = "../k8socks-config" }
thiserror = "2.0.17"
tokio.workspace = true
tracing = "0.1.41"
