[package]
name = "k8socks-config"
version = "0.1.0"
edition = "2024"

[dependencies]
k8socks-traits = { path = "../k8socks-traits" }
directories = "6.0.0"
thiserror = "2.0.17"
serde_json = "1.0.145"
serde = { version = "1.0.228", features = ["derive"] }
merge = "0.2.0"