[package]
name = "k8socks-ssh"
version = "0.1.0"
edition = "2024"

[dependencies]
k8socks-traits = { path = "../k8socks-traits" }
async-trait = "0.1.89"
thiserror = "2.0.17"
tokio = "1.38.0"
tracing = "0.1.41"