[package]
name = "k8socks-config"
version = "0.1.0"
edition = "2024"

[dependencies]
directories = "6.0.0"
merge = "0.2.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
thiserror = "2.0.17"
